In [1]:

import pandas as pd
import numpy as np

# Load feature-engineered dataset
df = pd.read_csv("../data/processed/student_habits_feature_engineered.csv")

# Display first few rows
df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,performance_category,risk_level
0,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2,At Risk,High Risk
1,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0,High Performer,Low Risk
2,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3,At Risk,High Risk
3,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8,At Risk,High Risk
4,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4,Average Performer,Medium Risk

In [2]:
# Check dataset shape and columns
print("Dataset Shape:", df.shape)

# Display all columns
df.columns

Dataset Shape: (1000, 17)

Index(['age', 'gender', 'study_hours_per_day', 'social_media_hours',
       'netflix_hours', 'part_time_job', 'attendance_percentage',
       'sleep_hours', 'diet_quality', 'exercise_frequency',
       'parental_education_level', 'internet_quality', 'mental_health_rating',
       'extracurricular_participation', 'exam_score', 'performance_category',
       'risk_level'],
      dtype='object')

In [3]:
# Create academic risk level based on exam score
# This will be useful for dashboard reporting

def assign_risk_level(score):
    if score >= 80:
        return "Low Risk"
    elif score >= 60:
        return "Medium Risk"
    else:
        return "High Risk"

# Apply function to create new column
df["academic_risk_level"] = df["exam_score"].apply(assign_risk_level)

# Check distribution of risk levels
df["academic_risk_level"].value_counts()

academic_risk_level
Medium Risk    443
High Risk      280
Low Risk       277
Name: count, dtype: int64

In [4]:
# Create personalized recommendations based on student habits
# This function checks each student's lifestyle and academic behavior

def generate_recommendations(row):
    
    recommendations = []
    
    # Study hours recommendation
    if row["study_hours_per_day"] < 2:
        recommendations.append("Increase daily study hours to at least 2-3 hours.")
    
    # Social media recommendation
    if row["social_media_hours"] > 3:
        recommendations.append("Reduce social media usage to improve focus.")
    
    # Netflix / entertainment recommendation
    if row["netflix_hours"] > 2:
        recommendations.append("Reduce entertainment screen time.")
    
    # Attendance recommendation
    if row["attendance_percentage"] < 75:
        recommendations.append("Improve class attendance to at least 80%.")
    
    # Sleep recommendation
    if row["sleep_hours"] < 6:
        recommendations.append("Improve sleep routine and aim for 7-8 hours of sleep.")
    
    # Mental health recommendation
    if row["mental_health_rating"] < 5:
        recommendations.append("Focus on mental well-being and seek support if needed.")
    
    # Exercise recommendation
    if row["exercise_frequency"] < 2:
        recommendations.append("Increase weekly physical activity for better balance.")
    
    # Diet recommendation
    if row["diet_quality"] == "Poor":
        recommendations.append("Improve diet quality to support better academic performance.")
    
    # Internet quality recommendation
    if row["internet_quality"] == "Poor":
        recommendations.append("Improve internet access or use campus resources for online learning.")
    
    # If no issues are detected
    if len(recommendations) == 0:
        recommendations.append("Maintain current positive study and lifestyle habits.")
    
    return recommendations

In [5]:
# Generate recommendations for every student
df["recommendations"] = df.apply(generate_recommendations, axis=1)

# Display sample results
df[["exam_score", "academic_risk_level", "recommendations"]].head()

,exam_score,academic_risk_level,recommendations
0,56.2,High Risk,[Increase daily study hours to at least 2-3 ho...
1,100.0,Low Risk,"[Reduce entertainment screen time., Improve sl..."
2,34.3,High Risk,[Increase daily study hours to at least 2-3 ho...
3,26.8,High Risk,[Increase daily study hours to at least 2-3 ho...
4,66.4,Medium Risk,"[Reduce social media usage to improve focus., ..."

In [6]:
# Create a simplified student report for dashboard use

student_report = df[
    [
        "age",
        "gender",
        "study_hours_per_day",
        "social_media_hours",
        "netflix_hours",
        "attendance_percentage",
        "sleep_hours",
        "mental_health_rating",
        "exercise_frequency",
        "diet_quality",
        "internet_quality",
        "exam_score",
        "academic_risk_level",
        "recommendations"
    ]
]

# View report
student_report.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,mental_health_rating,exercise_frequency,diet_quality,internet_quality,exam_score,academic_risk_level,recommendations
0,23,Female,0.0,1.2,1.1,85.0,8.0,8,6,Fair,Average,56.2,High Risk,[Increase daily study hours to at least 2-3 ho...
1,20,Female,6.9,2.8,2.3,97.3,4.6,8,6,Good,Average,100.0,Low Risk,"[Reduce entertainment screen time., Improve sl..."
2,21,Male,1.4,3.1,1.3,94.8,8.0,1,1,Poor,Poor,34.3,High Risk,[Increase daily study hours to at least 2-3 ho...
3,23,Female,1.0,3.9,1.0,71.0,9.2,1,4,Poor,Good,26.8,High Risk,[Increase daily study hours to at least 2-3 ho...
4,19,Female,5.0,4.4,0.5,90.9,4.9,1,3,Fair,Good,66.4,Medium Risk,"[Reduce social media usage to improve focus., ..."

In [7]:
# Count students in each academic risk level

risk_summary = df["academic_risk_level"].value_counts().reset_index()

risk_summary.columns = ["Risk Level", "Student Count"]

risk_summary

    Risk Level  Student Count
0  Medium Risk            443
1    High Risk            280
2     Low Risk            277

In [8]:
# Analyze average habits for each risk group

risk_habit_summary = df.groupby("academic_risk_level")[
    [
        "study_hours_per_day",
        "social_media_hours",
        "netflix_hours",
        "attendance_percentage",
        "sleep_hours",
        "mental_health_rating",
        "exercise_frequency",
        "exam_score"
    ]
].mean().round(2)

risk_habit_summary

,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,mental_health_rating,exercise_frequency,exam_score
academic_risk_level,,,,,,,,
High Risk,2.05,2.74,2.05,83.36,6.28,4.43,2.73,48.74
Low Risk,5.03,2.20,1.61,85.50,6.68,6.60,3.42,90.11
Medium Risk,3.57,2.54,1.81,83.76,6.46,5.35,3.00,69.96

In [9]:
# Save reports for the Streamlit dashboard

student_report.to_csv(
    "../data/processed/student_risk_report.csv",
    index=False
)

risk_summary.to_csv(
    "../data/processed/risk_summary.csv",
    index=False
)

risk_habit_summary.to_csv(
    "../data/processed/risk_habit_summary.csv"
)

print("Student risk reports saved successfully!")

Student risk reports saved successfully!

In [10]:
# Test recommendation system using one sample student

sample_student = df.iloc[0]

print("Exam Score:", sample_student["exam_score"])
print("Risk Level:", sample_student["academic_risk_level"])

print("\nRecommendations:")
for rec in sample_student["recommendations"]:
    print("-", rec)

Exam Score: 56.2
Risk Level: High Risk

Recommendations:
- Increase daily study hours to at least 2-3 hours.

In [11]:
# This function will be used later in the Streamlit dashboard
# It generates recommendations for a new student profile

def predict_student_recommendations(
    study_hours_per_day,
    social_media_hours,
    netflix_hours,
    attendance_percentage,
    sleep_hours,
    mental_health_rating,
    exercise_frequency,
    diet_quality,
    internet_quality
):
    
    recommendations = []
    
    if study_hours_per_day < 2:
        recommendations.append("Increase daily study hours to at least 2-3 hours.")
    
    if social_media_hours > 3:
        recommendations.append("Reduce social media usage to improve focus.")
    
    if netflix_hours > 2:
        recommendations.append("Reduce entertainment screen time.")
    
    if attendance_percentage < 75:
        recommendations.append("Improve class attendance to at least 80%.")
    
    if sleep_hours < 6:
        recommendations.append("Improve sleep routine and aim for 7-8 hours of sleep.")
    
    if mental_health_rating < 5:
        recommendations.append("Focus on mental well-being and seek support if needed.")
    
    if exercise_frequency < 2:
        recommendations.append("Increase weekly physical activity for better balance.")
    
    if diet_quality == "Poor":
        recommendations.append("Improve diet quality to support better academic performance.")
    
    if internet_quality == "Poor":
        recommendations.append("Improve internet access or use campus resources for online learning.")
    
    if len(recommendations) == 0:
        recommendations.append("Maintain current positive study and lifestyle habits.")
    
    return recommendations

In [12]:
# Test the function with a sample student profile

test_recommendations = predict_student_recommendations(
    study_hours_per_day=1,
    social_media_hours=4,
    netflix_hours=3,
    attendance_percentage=65,
    sleep_hours=5,
    mental_health_rating=4,
    exercise_frequency=1,
    diet_quality="Poor",
    internet_quality="Average"
)

print("Recommendations for sample student:")

for rec in test_recommendations:
    print("-", rec)

Recommendations for sample student:
- Increase daily study hours to at least 2-3 hours.
- Reduce social media usage to improve focus.
- Reduce entertainment screen time.
- Improve class attendance to at least 80%.
- Improve sleep routine and aim for 7-8 hours of sleep.
- Focus on mental well-being and seek support if needed.
- Increase weekly physical activity for better balance.
- Improve diet quality to support better academic performance.

In [ ]:
## Student Risk and Recommendation Summary

- Created academic risk levels based on exam scores.
- Built a rule-based recommendation system using study habits, lifestyle factors, attendance, sleep, mental health, and internet quality.
- Generated student-level risk reports for dashboard use.
- Created summary tables showing risk distribution and average habits by risk group.
- Saved processed reports for the Streamlit application.

This notebook converts the machine learning project into a decision-support system by providing personalized academic improvement recommendations.